// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/gallery.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Album messages
type CreateAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlbumRequest) Reset() {
	*x = CreateAlbumRequest{}
	mi := &file_proto_gallery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbumRequest) ProtoMessage() {}

func (x *CreateAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbumRequest.ProtoReflect.Descriptor instead.
func (*CreateAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAlbumRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlbumRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAlbumRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlbumResponse) Reset() {
	*x = CreateAlbumResponse{}
	mi := &file_proto_gallery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbumResponse) ProtoMessage() {}

func (x *CreateAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbumResponse.ProtoReflect.Descriptor instead.
func (*CreateAlbumResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAlbumResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAlbumsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumsByUserRequest) Reset() {
	*x = GetAlbumsByUserRequest{}
	mi := &file_proto_gallery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumsByUserRequest) ProtoMessage() {}

func (x *GetAlbumsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumsByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlbumsByUserRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetAlbumsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Albums        []*Album               `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumsByUserResponse) Reset() {
	*x = GetAlbumsByUserResponse{}
	mi := &file_proto_gallery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumsByUserResponse) ProtoMessage() {}

func (x *GetAlbumsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumsByUserResponse.ProtoReflect.Descriptor instead.
func (*GetAlbumsByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{3}
}

func (x *GetAlbumsByUserResponse) GetAlbums() []*Album {
	if x != nil {
		return x.Albums
	}
	return nil
}

type UpdateAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumId       uint32                 `protobuf:"varint,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlbumRequest) Reset() {
	*x = UpdateAlbumRequest{}
	mi := &file_proto_gallery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlbumRequest) ProtoMessage() {}

func (x *UpdateAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlbumRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAlbumRequest) GetAlbumId() uint32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

func (x *UpdateAlbumRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAlbumRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlbumResponse) Reset() {
	*x = UpdateAlbumResponse{}
	mi := &file_proto_gallery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlbumResponse) ProtoMessage() {}

func (x *UpdateAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlbumResponse.ProtoReflect.Descriptor instead.
func (*UpdateAlbumResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAlbumResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumId       uint32                 `protobuf:"varint,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlbumRequest) Reset() {
	*x = DeleteAlbumRequest{}
	mi := &file_proto_gallery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlbumRequest) ProtoMessage() {}

func (x *DeleteAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlbumRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAlbumRequest) GetAlbumId() uint32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

type DeleteAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlbumResponse) Reset() {
	*x = DeleteAlbumResponse{}
	mi := &file_proto_gallery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlbumResponse) ProtoMessage() {}

func (x *DeleteAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlbumResponse.ProtoReflect.Descriptor instead.
func (*DeleteAlbumResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAlbumResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPrivateAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumId       uint32                 `protobuf:"varint,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateAlbumRequest) Reset() {
	*x = GetPrivateAlbumRequest{}
	mi := &file_proto_gallery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateAlbumRequest) ProtoMessage() {}

func (x *GetPrivateAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateAlbumRequest.ProtoReflect.Descriptor instead.
func (*GetPrivateAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{8}
}

func (x *GetPrivateAlbumRequest) GetAlbumId() uint32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

type GetPrivateAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         *Album                 `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateAlbumResponse) Reset() {
	*x = GetPrivateAlbumResponse{}
	mi := &file_proto_gallery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateAlbumResponse) ProtoMessage() {}

func (x *GetPrivateAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateAlbumResponse.ProtoReflect.Descriptor instead.
func (*GetPrivateAlbumResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{9}
}

func (x *GetPrivateAlbumResponse) GetAlbum() *Album {
	if x != nil {
		return x.Album
	}
	return nil
}

// Media messages
type AddMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AlbumId       uint32                 `protobuf:"varint,2,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	FileData      []byte                 `protobuf:"bytes,3,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMediaRequest) Reset() {
	*x = AddMediaRequest{}
	mi := &file_proto_gallery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMediaRequest) ProtoMessage() {}

func (x *AddMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMediaRequest.ProtoReflect.Descriptor instead.
func (*AddMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{10}
}

func (x *AddMediaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMediaRequest) GetAlbumId() uint32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

func (x *AddMediaRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type AddMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMediaResponse) Reset() {
	*x = AddMediaResponse{}
	mi := &file_proto_gallery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMediaResponse) ProtoMessage() {}

func (x *AddMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMediaResponse.ProtoReflect.Descriptor instead.
func (*AddMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{11}
}

func (x *AddMediaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMediaByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaByUserRequest) Reset() {
	*x = GetMediaByUserRequest{}
	mi := &file_proto_gallery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaByUserRequest) ProtoMessage() {}

func (x *GetMediaByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaByUserRequest.ProtoReflect.Descriptor instead.
func (*GetMediaByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{12}
}

func (x *GetMediaByUserRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMediaByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaList     []*Media               `protobuf:"bytes,1,rep,name=media_list,json=mediaList,proto3" json:"media_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaByUserResponse) Reset() {
	*x = GetMediaByUserResponse{}
	mi := &file_proto_gallery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaByUserResponse) ProtoMessage() {}

func (x *GetMediaByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaByUserResponse.ProtoReflect.Descriptor instead.
func (*GetMediaByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{13}
}

func (x *GetMediaByUserResponse) GetMediaList() []*Media {
	if x != nil {
		return x.MediaList
	}
	return nil
}

type MarkAsPrivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       uint32                 `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsPrivateRequest) Reset() {
	*x = MarkAsPrivateRequest{}
	mi := &file_proto_gallery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsPrivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsPrivateRequest) ProtoMessage() {}

func (x *MarkAsPrivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsPrivateRequest.ProtoReflect.Descriptor instead.
func (*MarkAsPrivateRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{14}
}

func (x *MarkAsPrivateRequest) GetMediaId() uint32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *MarkAsPrivateRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type MarkAsPrivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsPrivateResponse) Reset() {
	*x = MarkAsPrivateResponse{}
	mi := &file_proto_gallery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsPrivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsPrivateResponse) ProtoMessage() {}

func (x *MarkAsPrivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsPrivateResponse.ProtoReflect.Descriptor instead.
func (*MarkAsPrivateResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{15}
}

func (x *MarkAsPrivateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPrivateMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateMediaRequest) Reset() {
	*x = GetPrivateMediaRequest{}
	mi := &file_proto_gallery_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateMediaRequest) ProtoMessage() {}

func (x *GetPrivateMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateMediaRequest.ProtoReflect.Descriptor instead.
func (*GetPrivateMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{16}
}

func (x *GetPrivateMediaRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetPrivateMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []*Media               `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateMediaResponse) Reset() {
	*x = GetPrivateMediaResponse{}
	mi := &file_proto_gallery_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateMediaResponse) ProtoMessage() {}

func (x *GetPrivateMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateMediaResponse.ProtoReflect.Descriptor instead.
func (*GetPrivateMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{17}
}

func (x *GetPrivateMediaResponse) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type DownloadMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       uint32                 `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadMediaRequest) Reset() {
	*x = DownloadMediaRequest{}
	mi := &file_proto_gallery_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMediaRequest) ProtoMessage() {}

func (x *DownloadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMediaRequest.ProtoReflect.Descriptor instead.
func (*DownloadMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{18}
}

func (x *DownloadMediaRequest) GetMediaId() uint32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type DownloadMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadMediaResponse) Reset() {
	*x = DownloadMediaResponse{}
	mi := &file_proto_gallery_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMediaResponse) ProtoMessage() {}

func (x *DownloadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMediaResponse.ProtoReflect.Descriptor instead.
func (*DownloadMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{19}
}

func (x *DownloadMediaResponse) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type DeleteMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       uint32                 `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_proto_gallery_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteMediaRequest) GetMediaId() uint32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type DeleteMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaResponse) Reset() {
	*x = DeleteMediaResponse{}
	mi := &file_proto_gallery_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaResponse) ProtoMessage() {}

func (x *DeleteMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteMediaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// User messages
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_gallery_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{22}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_proto_gallery_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{23}
}

func (x *CreateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Data structures
type Album struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserId        uint32                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Media         []*Media               `protobuf:"bytes,5,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_proto_gallery_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{24}
}

func (x *Album) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Album) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Album) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Album) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Album) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AlbumId       uint32                 `protobuf:"varint,3,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	FileSize      uint32                 `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_proto_gallery_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{25}
}

func (x *Media) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Media) GetAlbumId() uint32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

func (x *Media) GetFileSize() uint32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type MediaGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []*Media               `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaGroup) Reset() {
	*x = MediaGroup{}
	mi := &file_proto_gallery_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaGroup) ProtoMessage() {}

func (x *MediaGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaGroup.ProtoReflect.Descriptor instead.
func (*MediaGroup) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{26}
}

func (x *MediaGroup) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type DetectSimilarMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumId       uint32                 `protobuf:"varint,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectSimilarMediaRequest) Reset() {
	*x = DetectSimilarMediaRequest{}
	mi := &file_proto_gallery_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectSimilarMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectSimilarMediaRequest) ProtoMessage() {}

func (x *DetectSimilarMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectSimilarMediaRequest.ProtoReflect.Descriptor instead.
func (*DetectSimilarMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{27}
}

func (x *DetectSimilarMediaRequest) GetAlbumId() uint32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

type DetectSimilarMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*MediaGroup          `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectSimilarMediaResponse) Reset() {
	*x = DetectSimilarMediaResponse{}
	mi := &file_proto_gallery_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectSimilarMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectSimilarMediaResponse) ProtoMessage() {}

func (x *DetectSimilarMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectSimilarMediaResponse.ProtoReflect.Descriptor instead.
func (*DetectSimilarMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{28}
}

func (x *DetectSimilarMediaResponse) GetGroups() []*MediaGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_proto_gallery_proto protoreflect.FileDescriptor

const file_proto_gallery_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gallery.proto\x12\x05proto\"c\n" +
	"\x12CreateAlbumRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"/\n" +
	"\x13CreateAlbumResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\x16GetAlbumsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"?\n" +
	"\x17GetAlbumsByUserResponse\x12$\n" +
	"\x06albums\x18\x01 \x03(\v2\f.proto.AlbumR\x06albums\"e\n" +
	"\x12UpdateAlbumRequest\x12\x19\n" +
	"\balbum_id\x18\x01 \x01(\rR\aalbumId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"/\n" +
	"\x13UpdateAlbumResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"/\n" +
	"\x12DeleteAlbumRequest\x12\x19\n" +
	"\balbum_id\x18\x01 \x01(\rR\aalbumId\"/\n" +
	"\x13DeleteAlbumResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"3\n" +
	"\x16GetPrivateAlbumRequest\x12\x19\n" +
	"\balbum_id\x18\x01 \x01(\rR\aalbumId\"=\n" +
	"\x17GetPrivateAlbumResponse\x12\"\n" +
	"\x05album\x18\x01 \x01(\v2\f.proto.AlbumR\x05album\"]\n" +
	"\x0fAddMediaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\balbum_id\x18\x02 \x01(\rR\aalbumId\x12\x1b\n" +
	"\tfile_data\x18\x03 \x01(\fR\bfileData\",\n" +
	"\x10AddMediaResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"0\n" +
	"\x15GetMediaByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"E\n" +
	"\x16GetMediaByUserResponse\x12+\n" +
	"\n" +
	"media_list\x18\x01 \x03(\v2\f.proto.MediaR\tmediaList\"C\n" +
	"\x14MarkAsPrivateRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\rR\amediaId\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\"1\n" +
	"\x15MarkAsPrivateResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\x16GetPrivateMediaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"=\n" +
	"\x17GetPrivateMediaResponse\x12\"\n" +
	"\x05media\x18\x01 \x03(\v2\f.proto.MediaR\x05media\"1\n" +
	"\x14DownloadMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\rR\amediaId\"4\n" +
	"\x15DownloadMediaResponse\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\"/\n" +
	"\x12DeleteMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\rR\amediaId\"/\n" +
	"\x13DeleteMediaResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"E\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\".\n" +
	"\x12CreateUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x8a\x01\n" +
	"\x05Album\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\rR\x06userId\x12\"\n" +
	"\x05media\x18\x05 \x03(\v2\f.proto.MediaR\x05media\"c\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\balbum_id\x18\x03 \x01(\rR\aalbumId\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\rR\bfileSize\"0\n" +
	"\n" +
	"MediaGroup\x12\"\n" +
	"\x05media\x18\x01 \x03(\v2\f.proto.MediaR\x05media\"6\n" +
	"\x19DetectSimilarMediaRequest\x12\x19\n" +
	"\balbum_id\x18\x01 \x01(\rR\aalbumId\"G\n" +
	"\x1aDetectSimilarMediaResponse\x12)\n" +
	"\x06groups\x18\x01 \x03(\v2\x11.proto.MediaGroupR\x06groups2\x84\x03\n" +
	"\fAlbumService\x12D\n" +
	"\vCreateAlbum\x12\x19.proto.CreateAlbumRequest\x1a\x1a.proto.CreateAlbumResponse\x12P\n" +
	"\x0fGetAlbumsByUser\x12\x1d.proto.GetAlbumsByUserRequest\x1a\x1e.proto.GetAlbumsByUserResponse\x12D\n" +
	"\vUpdateAlbum\x12\x19.proto.UpdateAlbumRequest\x1a\x1a.proto.UpdateAlbumResponse\x12D\n" +
	"\vDeleteAlbum\x12\x19.proto.DeleteAlbumRequest\x1a\x1a.proto.DeleteAlbumResponse\x12P\n" +
	"\x0fGetPrivateAlbum\x12\x1d.proto.GetPrivateAlbumRequest\x1a\x1e.proto.GetPrivateAlbumResponse2\xa5\x04\n" +
	"\fMediaService\x12;\n" +
	"\bAddMedia\x12\x16.proto.AddMediaRequest\x1a\x17.proto.AddMediaResponse\x12M\n" +
	"\x0eGetMediaByUser\x12\x1c.proto.GetMediaByUserRequest\x1a\x1d.proto.GetMediaByUserResponse\x12J\n" +
	"\rMarkAsPrivate\x12\x1b.proto.MarkAsPrivateRequest\x1a\x1c.proto.MarkAsPrivateResponse\x12P\n" +
	"\x0fGetPrivateMedia\x12\x1d.proto.GetPrivateMediaRequest\x1a\x1e.proto.GetPrivateMediaResponse\x12J\n" +
	"\rDownloadMedia\x12\x1b.proto.DownloadMediaRequest\x1a\x1c.proto.DownloadMediaResponse\x12D\n" +
	"\vDeleteMedia\x12\x19.proto.DeleteMediaRequest\x1a\x1a.proto.DeleteMediaResponse\x12Y\n" +
	"\x12DetectSimilarMedia\x12 .proto.DetectSimilarMediaRequest\x1a!.proto.DetectSimilarMediaResponse2P\n" +
	"\vUserService\x12A\n" +
	"\n" +
	"CreateUser\x12\x18.proto.CreateUserRequest\x1a\x19.proto.CreateUserResponseB\x0eZ\f/proto;protob\x06proto3"

var (
	file_proto_gallery_proto_rawDescOnce sync.Once
	file_proto_gallery_proto_rawDescData []byte
)

func file_proto_gallery_proto_rawDescGZIP() []byte {
	file_proto_gallery_proto_rawDescOnce.Do(func() {
		file_proto_gallery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gallery_proto_rawDesc), len(file_proto_gallery_proto_rawDesc)))
	})
	return file_proto_gallery_proto_rawDescData
}

var file_proto_gallery_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_gallery_proto_goTypes = []any{
	(*CreateAlbumRequest)(nil),         // 0: proto.CreateAlbumRequest
	(*CreateAlbumResponse)(nil),        // 1: proto.CreateAlbumResponse
	(*GetAlbumsByUserRequest)(nil),     // 2: proto.GetAlbumsByUserRequest
	(*GetAlbumsByUserResponse)(nil),    // 3: proto.GetAlbumsByUserResponse
	(*UpdateAlbumRequest)(nil),         // 4: proto.UpdateAlbumRequest
	(*UpdateAlbumResponse)(nil),        // 5: proto.UpdateAlbumResponse
	(*DeleteAlbumRequest)(nil),         // 6: proto.DeleteAlbumRequest
	(*DeleteAlbumResponse)(nil),        // 7: proto.DeleteAlbumResponse
	(*GetPrivateAlbumRequest)(nil),     // 8: proto.GetPrivateAlbumRequest
	(*GetPrivateAlbumResponse)(nil),    // 9: proto.GetPrivateAlbumResponse
	(*AddMediaRequest)(nil),            // 10: proto.AddMediaRequest
	(*AddMediaResponse)(nil),           // 11: proto.AddMediaResponse
	(*GetMediaByUserRequest)(nil),      // 12: proto.GetMediaByUserRequest
	(*GetMediaByUserResponse)(nil),     // 13: proto.GetMediaByUserResponse
	(*MarkAsPrivateRequest)(nil),       // 14: proto.MarkAsPrivateRequest
	(*MarkAsPrivateResponse)(nil),      // 15: proto.MarkAsPrivateResponse
	(*GetPrivateMediaRequest)(nil),     // 16: proto.GetPrivateMediaRequest
	(*GetPrivateMediaResponse)(nil),    // 17: proto.GetPrivateMediaResponse
	(*DownloadMediaRequest)(nil),       // 18: proto.DownloadMediaRequest
	(*DownloadMediaResponse)(nil),      // 19: proto.DownloadMediaResponse
	(*DeleteMediaRequest)(nil),         // 20: proto.DeleteMediaRequest
	(*DeleteMediaResponse)(nil),        // 21: proto.DeleteMediaResponse
	(*CreateUserRequest)(nil),          // 22: proto.CreateUserRequest
	(*CreateUserResponse)(nil),         // 23: proto.CreateUserResponse
	(*Album)(nil),                      // 24: proto.Album
	(*Media)(nil),                      // 25: proto.Media
	(*MediaGroup)(nil),                 // 26: proto.MediaGroup
	(*DetectSimilarMediaRequest)(nil),  // 27: proto.DetectSimilarMediaRequest
	(*DetectSimilarMediaResponse)(nil), // 28: proto.DetectSimilarMediaResponse
}
var file_proto_gallery_proto_depIdxs = []int32{
	24, // 0: proto.GetAlbumsByUserResponse.albums:type_name -> proto.Album
	24, // 1: proto.GetPrivateAlbumResponse.album:type_name -> proto.Album
	25, // 2: proto.GetMediaByUserResponse.media_list:type_name -> proto.Media
	25, // 3: proto.GetPrivateMediaResponse.media:type_name -> proto.Media
	25, // 4: proto.Album.media:type_name -> proto.Media
	25, // 5: proto.MediaGroup.media:type_name -> proto.Media
	26, // 6: proto.DetectSimilarMediaResponse.groups:type_name -> proto.MediaGroup
	0,  // 7: proto.AlbumService.CreateAlbum:input_type -> proto.CreateAlbumRequest
	2,  // 8: proto.AlbumService.GetAlbumsByUser:input_type -> proto.GetAlbumsByUserRequest
	4,  // 9: proto.AlbumService.UpdateAlbum:input_type -> proto.UpdateAlbumRequest
	6,  // 10: proto.AlbumService.DeleteAlbum:input_type -> proto.DeleteAlbumRequest
	8,  // 11: proto.AlbumService.GetPrivateAlbum:input_type -> proto.GetPrivateAlbumRequest
	10, // 12: proto.MediaService.AddMedia:input_type -> proto.AddMediaRequest
	12, // 13: proto.MediaService.GetMediaByUser:input_type -> proto.GetMediaByUserRequest
	14, // 14: proto.MediaService.MarkAsPrivate:input_type -> proto.MarkAsPrivateRequest
	16, // 15: proto.MediaService.GetPrivateMedia:input_type -> proto.GetPrivateMediaRequest
	18, // 16: proto.MediaService.DownloadMedia:input_type -> proto.DownloadMediaRequest
	20, // 17: proto.MediaService.DeleteMedia:input_type -> proto.DeleteMediaRequest
	27, // 18: proto.MediaService.DetectSimilarMedia:input_type -> proto.DetectSimilarMediaRequest
	22, // 19: proto.UserService.CreateUser:input_type -> proto.CreateUserRequest
	1,  // 20: proto.AlbumService.CreateAlbum:output_type -> proto.CreateAlbumResponse
	3,  // 21: proto.AlbumService.GetAlbumsByUser:output_type -> proto.GetAlbumsByUserResponse
	5,  // 22: proto.AlbumService.UpdateAlbum:output_type -> proto.UpdateAlbumResponse
	7,  // 23: proto.AlbumService.DeleteAlbum:output_type -> proto.DeleteAlbumResponse
	9,  // 24: proto.AlbumService.GetPrivateAlbum:output_type -> proto.GetPrivateAlbumResponse
	11, // 25: proto.MediaService.AddMedia:output_type -> proto.AddMediaResponse
	13, // 26: proto.MediaService.GetMediaByUser:output_type -> proto.GetMediaByUserResponse
	15, // 27: proto.MediaService.MarkAsPrivate:output_type -> proto.MarkAsPrivateResponse
	17, // 28: proto.MediaService.GetPrivateMedia:output_type -> proto.GetPrivateMediaResponse
	19, // 29: proto.MediaService.DownloadMedia:output_type -> proto.DownloadMediaResponse
	21, // 30: proto.MediaService.DeleteMedia:output_type -> proto.DeleteMediaResponse
	28, // 31: proto.MediaService.DetectSimilarMedia:output_type -> proto.DetectSimilarMediaResponse
	23, // 32: proto.UserService.CreateUser:output_type -> proto.CreateUserResponse
	20, // [20:33] is the sub-list for method output_type
	7,  // [7:20] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_gallery_proto_init() }
func file_proto_gallery_proto_init() {
	if File_proto_gallery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gallery_proto_rawDesc), len(file_proto_gallery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_gallery_proto_goTypes,
		DependencyIndexes: file_proto_gallery_proto_depIdxs,
		MessageInfos:      file_proto_gallery_proto_msgTypes,
	}.Build()
	File_proto_gallery_proto = out.File
	file_proto_gallery_proto_goTypes = nil
	file_proto_gallery_proto_depIdxs = nil
}
